import React, { useState, useEffect, useRef } from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  TextField,
  Box,
  Typography,
  Grid,
  Alert,
  CircularProgress,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Divider,
  Paper,
  List,
  ListItem,
  ListItemText,
  IconButton,
  ImageList,
  ImageListItem,
  ImageListItemBar,
  Chip,
} from '@mui/material';
import { Delete as DeleteIcon, CloudUpload as UploadIcon, ChevronLeft, ChevronRight, ZoomIn, ZoomOut } from '@mui/icons-material';
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Placeholder from '@tiptap/extension-placeholder';
import Link from '@tiptap/extension-link';
import Image from '@tiptap/extension-image';
import Underline from '@tiptap/extension-underline';
import { fatsAPI, referenceAPI } from '../services/api';
import { formatHSTTimestamp, getCurrentHSTForInput } from '../utils/timezone';
import MenuBar from './MenuBar';

// Get API base URL for constructing image URLs
const API_BASE_URL = process.env.REACT_APP_API_URL || 'http://localhost:8000';

const FATSDetail = ({ open, fatsId, onClose, onSave, mode = 'view', onFaultReferenceClick }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [fats, setFats] = useState(null);
  const [comments, setComments] = useState([]);
  const [images, setImages] = useState([]);
  const [uploadingImage, setUploadingImage] = useState(false);
  const [pendingImages, setPendingImages] = useState([]); // Images selected but not yet uploaded (for new entries)
  const [sections, setSections] = useState([]);
  const [staff, setStaff] = useState([]);
  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
  const [selectedImage, setSelectedImage] = useState(null); // For image preview modal
  const [imageZoom, setImageZoom] = useState(1); // Zoom level for image preview
  const [imagePosition, setImagePosition] = useState({ x: 0, y: 0 }); // Pan position when zoomed
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });
  const imageContainerRef = useRef(null);
  const fileInputRef = useRef(null);
  const createImageInputRef = useRef(null); // Separate ref for create form image upload
  const [formData, setFormData] = useState({
    idno: null, // Auto-generated by database
    issue: '',
    idescribe: '',
    solution: '',
    sdescribe: '',
    operator: '',
    status: 'Active',
    todo: '',
    section: '',
    section2: '.none',
    assigned_to: '',
    datein: getCurrentHSTForInput(),
  });

  const isViewMode = mode === 'view';

  // Tiptap editor for Issue Describe
  const editorIssue = useEditor({
    extensions: [
      StarterKit.configure({
        heading: {
          levels: [1, 2, 3],
        },
        link: false, // Disable default link to use custom Link extension
        underline: false, // Disable default underline to use custom Underline extension
      }),
      Underline,
      Placeholder.configure({
        placeholder: 'Describe the issue in detail...',
      }),
      Link.configure({
        openOnClick: false,
        autolink: true, // Automatically convert typed URLs to links
        linkOnPaste: true, // Auto-linkify pasted URLs
        HTMLAttributes: {
          class: 'text-blue-600 underline',
          target: '_blank',
          rel: 'noopener noreferrer',
        },
        validate: href => {
          // Allow internal fault links (#fault-XXXX) or standard URLs
          return href.startsWith('#fault-') || /^https?:\/\//.test(href);
        },
      }),
      Image,
    ],
    content: formData.idescribe || '',
    onUpdate: ({ editor }) => {
      setFormData((prev) => ({ ...prev, idescribe: editor.getHTML() }));
    },
    editorProps: {
      handlePaste: (view, event, slice) => {
        const text = event.clipboardData?.getData('text/plain');
        if (text) {
          // Check if the entire pasted text is a URL
          const urlRegex = /^https?:\/\/[^\s]+$/;
          if (urlRegex.test(text.trim())) {
            // Insert as a link
            const { state } = view;
            const { tr } = state;
            const link = state.schema.marks.link.create({ href: text.trim() });
            const textNode = state.schema.text(text.trim(), [link]);
            tr.replaceSelectionWith(textNode, false);
            view.dispatch(tr);
            return true; // Prevent default paste
          }
        }
        return false; // Use default paste for non-URL text
      },
    },
    editable: !isViewMode,
  });

  // Tiptap editor for Solution Describe
  const editorSolution = useEditor({
    extensions: [
      StarterKit.configure({
        heading: {
          levels: [1, 2, 3],
        },
        link: false, // Disable default link to use custom Link extension
        underline: false, // Disable default underline to use custom Underline extension
      }),
      Underline,
      Placeholder.configure({
        placeholder: 'Describe the solution in detail...',
      }),
      Link.configure({
        openOnClick: false,
        autolink: true, // Automatically convert pasted URLs to links
        linkOnPaste: true, // Auto-linkify pasted URLs
        HTMLAttributes: {
          class: 'text-blue-600 underline',
          target: '_blank',
          rel: 'noopener noreferrer',
        },
        validate: href => {
          // Allow internal fault links (#fault-XXXX) or standard URLs
          return href.startsWith('#fault-') || /^https?:\/\//.test(href);
        },
      }),
      Image,
    ],
    content: formData.sdescribe || '',
    onUpdate: ({ editor }) => {
      setFormData((prev) => ({ ...prev, sdescribe: editor.getHTML() }));
    },
    editorProps: {
      handlePaste: (view, event, slice) => {
        const text = event.clipboardData?.getData('text/plain');
        if (text) {
          // Check if the entire pasted text is a URL
          const urlRegex = /^https?:\/\/[^\s]+$/;
          if (urlRegex.test(text.trim())) {
            // Insert as a link
            const { state } = view;
            const { tr } = state;
            const link = state.schema.marks.link.create({ href: text.trim() });
            const textNode = state.schema.text(text.trim(), [link]);
            tr.replaceSelectionWith(textNode, false);
            view.dispatch(tr);
            return true; // Prevent default paste
          }
        }
        return false; // Use default paste for non-URL text
      },
    },
    editable: !isViewMode,
  });

  // Update editor content and editable state when dialog opens
  useEffect(() => {
    if (editorIssue && open) {
      // Update content if it changed
      const currentContent = editorIssue.getHTML();
      const newContent = formData.idescribe || '';
      if (currentContent !== newContent) {
        editorIssue.commands.setContent(newContent);
      }
      // Update editable state
      if (editorIssue.isEditable !== !isViewMode) {
        editorIssue.setOptions({ editable: !isViewMode });
      }
    }
  }, [open, editorIssue, formData.idescribe, isViewMode]);

  useEffect(() => {
    if (editorSolution && open) {
      // Update content if it changed
      const currentContent = editorSolution.getHTML();
      const newContent = formData.sdescribe || '';
      if (currentContent !== newContent) {
        editorSolution.commands.setContent(newContent);
      }
      // Update editable state
      if (editorSolution.isEditable !== !isViewMode) {
        editorSolution.setOptions({ editable: !isViewMode });
      }
    }
  }, [open, editorSolution, formData.sdescribe, isViewMode]);

      useEffect(() => {
        if (open) {
          // Load reference data (sections and staff)
          loadReferenceData();
          
          if (fatsId && (mode === 'view' || mode === 'edit')) {
            loadFATS();
          } else if (mode === 'create') {
            setFats(null);
            setImages([]);
            setPendingImages([]); // Clear pending images when creating new entry
            setFormData({
              idno: null, // Auto-generated by database
              issue: '',
              idescribe: '',
              solution: '',
              sdescribe: '',
              operator: 'mayank',
              status: 'Active',
              todo: '',
              section: '.none',
              section2: '.none',
              assigned_to: '',
              datein: getCurrentHSTForInput(),
            });
          }
        }
        
        // eslint-disable-next-line react-hooks/exhaustive-deps
      }, [open, fatsId, mode]);

  // Handle clicks on internal fault links in view mode
  useEffect(() => {
    if (!open || !isViewMode) return;

    const handleLinkClick = (e) => {
      const target = e.target.closest('a');
      if (!target) return;
      
      const href = target.getAttribute('href');
      
      // Check if it's an internal fault link (#fault-XXXX)
      if (href && href.startsWith('#fault-')) {
        e.preventDefault();
        e.stopPropagation();
        const faultId = href.replace('#fault-', '');
        const faultIdNum = parseInt(faultId);
        
        if (!isNaN(faultIdNum) && window.handleViewFATS) {
          // Close current dialog first
          onClose();
          // Open the linked fault
          window.handleViewFATS(faultIdNum);
        }
      }
    };

    // Add event listener to the dialog content
    const dialogContent = document.querySelector('[role="dialog"]');
    if (dialogContent) {
      dialogContent.addEventListener('click', handleLinkClick);
      return () => dialogContent.removeEventListener('click', handleLinkClick);
    }
  }, [open, isViewMode, onClose]);

  // Cleanup editors when component unmounts
  useEffect(() => {
    return () => {
      if (editorIssue) {
        editorIssue.destroy();
      }
      if (editorSolution) {
        editorSolution.destroy();
      }
    };
  }, []);

      const loadReferenceData = async () => {
        try {
          const [sectionsData, staffData] = await Promise.all([
            referenceAPI.getSections(),
            referenceAPI.getStaff()
          ]);
          setSections(sectionsData || []);
          setStaff(staffData || []);
        } catch (err) {
          console.warn('Failed to load reference data:', err);
          // Set defaults if API fails
          setSections(['.none', 'Telescope/Dome', 'Instruments/PFS', 'Dome/Environment']);
          setStaff(['mayank', 'letawsky', 'twin']);
        }
      };

      const loadImages = async () => {
        if (!fatsId) return;
        try {
          const imagesData = await fatsAPI.getImages(fatsId);
          setImages(imagesData || []);
        } catch (err) {
          console.warn('Could not load images:', err);
          setImages([]);
        }
      };

      const handleImageUpload = async (event) => {
        const file = event.target.files[0];
        if (!file) {
          return;
        }

        // Check if FATS entry exists (must be saved first)
        if (!fatsId) {
          setError('Please save the FATS entry first before uploading images');
          // Reset file input
          if (fileInputRef.current) {
            fileInputRef.current.value = '';
          }
          return;
        }

        // Validate file type
        const validImageTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
        if (!file.type.startsWith('image/') || !validImageTypes.includes(file.type)) {
          setError('Please select a valid image file (JPEG, PNG, GIF, or WebP)');
          // Reset file input
          if (fileInputRef.current) {
            fileInputRef.current.value = '';
          }
          return;
        }

        // Validate file size (10MB)
        const maxSize = 10 * 1024 * 1024; // 10MB
        if (file.size > maxSize) {
          setError(`Image size must be less than 10MB. Your file is ${(file.size / 1024 / 1024).toFixed(2)}MB`);
          // Reset file input
          if (fileInputRef.current) {
            fileInputRef.current.value = '';
          }
          return;
        }

        try {
          setUploadingImage(true);
          setError(null);
          if (process.env.NODE_ENV === 'development') {
            console.log('Uploading image:', file.name, 'Size:', (file.size / 1024).toFixed(2), 'KB');
          }
          await fatsAPI.uploadImage(fatsId, file);
          if (process.env.NODE_ENV === 'development') {
            console.log('Image uploaded successfully');
          }
          await loadImages(); // Reload images
          // Reset file input
          if (fileInputRef.current) {
            fileInputRef.current.value = '';
          }
        } catch (err) {
          console.error('Image upload error:', err);
          setError(err.response?.data?.detail || err.message || 'Failed to upload image. Please try again.');
        } finally {
          setUploadingImage(false);
        }
      };

      const handleDeleteImage = async (imageId) => {
        if (!window.confirm('Are you sure you want to delete this image?')) {
          return;
        }

        try {
          await fatsAPI.deleteImage(imageId);
          await loadImages(); // Reload images
        } catch (err) {
          setError(err.message || 'Failed to delete image');
        }
      };

      // Handle image selection in create form (before FATS entry is saved)
      const handleCreateFormImageSelect = (event) => {
        const files = Array.from(event.target.files || []);
        if (files.length === 0) {
          return;
        }

        const validImageTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
        const maxSize = 10 * 1024 * 1024; // 10MB
        const validFiles = [];
        const errors = [];

        files.forEach((file) => {
          // Validate file type
          if (!file.type.startsWith('image/') || !validImageTypes.includes(file.type)) {
            errors.push(`${file.name}: Invalid file type. Please select JPEG, PNG, GIF, or WebP.`);
            return;
          }

          // Validate file size
          if (file.size > maxSize) {
            errors.push(`${file.name}: File size (${(file.size / 1024 / 1024).toFixed(2)}MB) exceeds 10MB limit.`);
            return;
          }

          validFiles.push(file);
        });

        if (errors.length > 0) {
          setError(errors.join('\n'));
        }

        if (validFiles.length > 0) {
          setPendingImages((prev) => [...prev, ...validFiles]);
          setError(null);
        }

        // Reset file input
        if (createImageInputRef.current) {
          createImageInputRef.current.value = '';
        }
      };

      // Upload pending images after FATS entry is created (using bulk upload for efficiency)
      const uploadPendingImages = async (newFatsId) => {
        if (pendingImages.length === 0 || !newFatsId) {
          return;
        }

        try {
          setUploadingImage(true);
          setError(null);
          
          // Use bulk upload for better performance when multiple images
          if (pendingImages.length > 1) {
            if (process.env.NODE_ENV === 'development') {
              console.log(`Uploading ${pendingImages.length} images via bulk upload...`);
            }
            const fileList = new DataTransfer();
            pendingImages.forEach(file => fileList.items.add(file));
            await fatsAPI.uploadImages(newFatsId, fileList.files);
          } else {
            // Single image - use regular upload
            if (process.env.NODE_ENV === 'development') {
              console.log('Uploading single pending image:', pendingImages[0].name);
            }
            await fatsAPI.uploadImage(newFatsId, pendingImages[0]);
          }

          // Clear pending images and reload
          setPendingImages([]);
          await loadImages();
          if (process.env.NODE_ENV === 'development') {
            console.log('All pending images uploaded successfully');
          }
        } catch (err) {
          console.error('Error uploading pending images:', err);
          setError(err.response?.data?.detail || err.message || 'Some images failed to upload. You can upload them manually later.');
        } finally {
          setUploadingImage(false);
        }
      };

  // Capitalize first letter of a string (for operator names)
  const capitalizeFirst = (str) => {
    if (!str) return '';
    return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
  };

  // Format display value for operator: ".none" -> "None", otherwise capitalize first letter
  const formatOperatorDisplay = (value) => {
    if (value === '.none') return 'None';
    return capitalizeFirst(value);
  };

  // Format display value for section/section2: ".none" -> "None", otherwise keep as-is
  const formatSectionDisplay = (value) => {
    if (value === '.none') return 'None';
    return value;
  };

      const loadFATS = async () => {
        try {
          setLoading(true);
          setError(null);
          
          // Set a timeout for the entire load operation
          const timeoutPromise = new Promise((_, reject) => {
            setTimeout(() => reject(new Error('Request timeout: FATS entry took too long to load')), 10000);
          });
          
          const data = await Promise.race([
            fatsAPI.getById(fatsId),
            timeoutPromise
          ]);
          
          setFats(data);

          // Load comments if available (non-blocking)
          if (data.comments && Array.isArray(data.comments)) {
            setComments(data.comments);
          } else {
            // Try to load comments separately (non-blocking)
            fatsAPI.getComments(fatsId)
              .then(commentsData => setComments(commentsData || []))
              .catch(err => {
                console.warn('Could not load comments:', err);
                setComments([]);
              });
          }
          
          // Load images asynchronously (don't block main data loading)
          loadImages().catch(err => {
            console.warn('Could not load images:', err);
            setImages([]);
          });
      
          setFormData({
            idno: data.idno || '',
            issue: data.issue || '',
            idescribe: data.idescribe || '',
            solution: data.solution || '',
            sdescribe: data.sdescribe || '',
            operator: data.operator || 'mayank',
            status: data.status || 'Active',
            todo: data.todo || '',
            section: data.section || '.none',
            section2: data.section2 || '.none',
            assigned_to: data.assigned_to || '',
            datein: data.datein || getCurrentHSTForInput(),
          });
        } catch (err) {
          console.error('Error loading FATS:', err);
          setError(err.message || 'Failed to load FATS entry. Please try again.');
          setFats(null); // Clear fats to show error message
        } finally {
          setLoading(false);
        }
      };

  const handleChange = (field) => (e) => {
    const value = e.target ? e.target.value : e;
    setFormData({ ...formData, [field]: value });
  };

  // Update editors only when formData is loaded from API (not when user types)
  // Use a ref to track if we've initialized the editor content
  const editorIssueInitialized = useRef(false);
  const editorSolutionInitialized = useRef(false);
  const prevOpenRef = useRef(false);

  useEffect(() => {
    // Reset initialization flags when dialog opens
    if (open && !prevOpenRef.current) {
      editorIssueInitialized.current = false;
      editorSolutionInitialized.current = false;
    }
    prevOpenRef.current = open;
  }, [open]);

  useEffect(() => {
    if (editorIssue && open) {
      // Set content when dialog opens or when formData changes (from loading)
      const content = formData.idescribe || '';
      const currentContent = editorIssue.getHTML();
      
      // Only update if content is different and we haven't initialized yet
      // OR if we're loading existing data (fatsId exists)
      if (!editorIssueInitialized.current || (fatsId && content !== currentContent)) {
        if (content !== currentContent) {
          editorIssue.commands.setContent(content);
        }
        editorIssueInitialized.current = true;
      }
    }
  }, [open, editorIssue, formData.idescribe, fatsId]);

  useEffect(() => {
    if (editorSolution && open) {
      // Set content when dialog opens or when formData changes (from loading)
      const content = formData.sdescribe || '';
      const currentContent = editorSolution.getHTML();
      
      // Only update if content is different and we haven't initialized yet
      // OR if we're loading existing data (fatsId exists)
      if (!editorSolutionInitialized.current || (fatsId && content !== currentContent)) {
        if (content !== currentContent) {
          editorSolution.commands.setContent(content);
        }
        editorSolutionInitialized.current = true;
      }
    }
  }, [open, editorSolution, formData.sdescribe, fatsId]);


  const handleSaveClick = () => {
    // Show confirmation dialog first
    setConfirmDialogOpen(true);
  };

  const handleConfirmSave = async () => {
    setConfirmDialogOpen(false);
    try {
      setLoading(true);
      setError(null);
      
      // Get latest content from editors
      if (editorIssue) {
        formData.idescribe = editorIssue.getHTML();
      }
      if (editorSolution) {
        formData.sdescribe = editorSolution.getHTML();
      }
      
      let newFatsId = fatsId;
      
      if (mode === 'create') {
        // Prepare data for creation - remove idno (always auto-generated) and datein
        const createData = { ...formData };
        // Remove idno (always auto-generated by database)
        delete createData.idno;
        // Remove datein (will be set by backend)
        delete createData.datein;
        // Ensure section is included if provided
        if (!createData.section) {
          createData.section = null;
        }
        const createdFats = await fatsAPI.create(createData, true);
        newFatsId = createdFats.idno || createdFats.id; // Get the new FATS ID
      } else {
        await fatsAPI.update(fatsId, formData);
      }
      
      // Upload pending images if any were selected
      if (pendingImages.length > 0 && newFatsId) {
        await uploadPendingImages(newFatsId);
      }
      
      if (onSave) onSave();
      onClose();
    } catch (err) {
      setError(err.message || 'Failed to save FATS entry');
    } finally {
      setLoading(false);
    }
  };

  const handleCancelConfirm = () => {
    setConfirmDialogOpen(false);
  };

  // Strip HTML tags from text
  const stripHtml = (html) => {
    if (!html) return '';
    const tmp = document.createElement('div');
    tmp.innerHTML = html;
    const text = tmp.textContent || tmp.innerText || '';
    return text.trim().replace(/\s+/g, ' ');
  };

  // Remove date prefixes from description (e.g., "(9/16/2025) Moritani:")
  const cleanDescription = (text) => {
    if (!text) return '';
    // Remove patterns like "(MM/DD/YYYY) Name:" or "(MM/DD/YY) Name:"
    // Matches: (9/16/2025) Moritani: or (8/28/2025) Kumura-san:
    const datePattern = /^\(\d{1,2}\/\d{1,2}\/\d{2,4}\)\s*[^:]+:\s*/i;
    return text.replace(datePattern, '').trim();
  };

  // Strip HTML for preview in confirmation dialog
  const stripHtmlForPreview = (html) => {
    if (!html) return 'N/A';
    const tmp = document.createElement('div');
    tmp.innerHTML = html;
    const text = tmp.textContent || tmp.innerText || '';
    return text.trim().substring(0, 200) + (text.length > 200 ? '...' : '');
  };

  return (
    <>
      {/* Confirmation Dialog */}
      <Dialog
        open={confirmDialogOpen}
        onClose={handleCancelConfirm}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          {mode === 'create' ? 'Confirm Create FATS Entry' : 'Confirm Update FATS Entry'}
        </DialogTitle>
        <DialogContent>
          <Typography variant="body1" sx={{ mb: 2, fontWeight: 'bold' }}>
            Please review the information below before saving:
          </Typography>
          <Box sx={{ mt: 2 }}>
            <Grid container spacing={2}>
              {mode !== 'create' && (
                <Grid item xs={12}>
                  <Typography variant="subtitle2" color="text.secondary">IDNo:</Typography>
                  <Typography variant="body1">{formData.idno || 'N/A'}</Typography>
                </Grid>
              )}
              <Grid item xs={12} sm={6}>
                <Typography variant="subtitle2" color="text.secondary">Operator:</Typography>
                <Typography variant="body1">{formData.operator || 'N/A'}</Typography>
              </Grid>
              <Grid item xs={12} sm={6}>
                <Typography variant="subtitle2" color="text.secondary">Status:</Typography>
                <Typography variant="body1">{formData.status || 'N/A'}</Typography>
              </Grid>
              <Grid item xs={12} sm={6}>
                <Typography variant="subtitle2" color="text.secondary">Section:</Typography>
                <Typography variant="body1">{formData.section === '.none' ? 'None' : (formData.section || 'N/A')}</Typography>
              </Grid>
              <Grid item xs={12} sm={6}>
                <Typography variant="subtitle2" color="text.secondary">Section2:</Typography>
                <Typography variant="body1">{formData.section2 === '.none' ? 'None' : (formData.section2 || 'N/A')}</Typography>
              </Grid>
              <Grid item xs={12}>
                <Typography variant="subtitle2" color="text.secondary">Issue:</Typography>
                <Typography variant="body1">{formData.issue || 'N/A'}</Typography>
              </Grid>
              <Grid item xs={12}>
                <Typography variant="subtitle2" color="text.secondary">Issue Description:</Typography>
                <Typography variant="body2" sx={{ 
                  maxHeight: 100, 
                  overflow: 'auto',
                  p: 1,
                  bgcolor: '#f5f5f5',
                  borderRadius: 1,
                  whiteSpace: 'pre-wrap'
                }}>
                  {stripHtmlForPreview(editorIssue?.getHTML() || formData.idescribe || '')}
                </Typography>
              </Grid>
              <Grid item xs={12} sm={6}>
                <Typography variant="subtitle2" color="text.secondary">Action:</Typography>
                <Typography variant="body1">{formData.todo || 'N/A'}</Typography>
              </Grid>
              <Grid item xs={12} sm={6}>
                <Typography variant="subtitle2" color="text.secondary">Solution:</Typography>
                <Typography variant="body1">{formData.solution || 'N/A'}</Typography>
              </Grid>
              <Grid item xs={12}>
                <Typography variant="subtitle2" color="text.secondary">Solution Description:</Typography>
                <Typography variant="body2" sx={{ 
                  maxHeight: 100, 
                  overflow: 'auto',
                  p: 1,
                  bgcolor: '#f5f5f5',
                  borderRadius: 1,
                  whiteSpace: 'pre-wrap'
                }}>
                  {stripHtmlForPreview(editorSolution?.getHTML() || formData.sdescribe || '')}
                </Typography>
              </Grid>
            </Grid>
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleCancelConfirm} color="inherit">
            Cancel
          </Button>
          <Button
            onClick={handleConfirmSave}
            variant="contained"
            color="primary"
            disabled={loading}
          >
            {loading ? 'Saving...' : 'Confirm & Save'}
          </Button>
        </DialogActions>
      </Dialog>

      {/* Main FATS Detail Dialog */}
      <Dialog open={open} onClose={onClose} maxWidth="lg" fullWidth>
      {mode === 'create' && (
        <Box sx={{ p: 2, display: 'flex', justifyContent: 'space-between', borderBottom: 1, borderColor: 'divider' }}>
          <Button
            variant="contained"
            onClick={handleSaveClick}
            disabled={loading}
            sx={{ minWidth: 100 }}
          >
            {loading ? 'Saving...' : 'Save'}
          </Button>
          <Button
            variant="outlined"
            onClick={onClose}
            sx={{ minWidth: 100 }}
          >
            Cancel
          </Button>
        </Box>
      )}
      {mode !== 'create' && (
        <DialogTitle>
          {mode === 'view' ? `FATS Entry: ${fatsId}` : `Edit FATS Entry: ${fatsId}`}
        </DialogTitle>
      )}
      <DialogContent sx={{ pt: mode === 'create' ? 2 : 0 }}>
        {loading && !fats && !error && mode !== 'create' && (
          <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', p: 4 }}>
            <CircularProgress />
            <Typography variant="body2" sx={{ mt: 2, color: 'text.secondary' }}>
              Loading FATS entry...
            </Typography>
          </Box>
        )}
        
        {loading && mode === 'create' && (
          <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', p: 4 }}>
            <CircularProgress />
            <Typography variant="body2" sx={{ mt: 2, color: 'text.secondary' }}>
              Creating FATS entry...
            </Typography>
          </Box>
        )}

        {error && (
          <Box sx={{ p: 4 }}>
            <Alert severity="error" sx={{ mb: 2 }}>
              {error}
            </Alert>
            <Button
              variant="outlined"
              onClick={() => {
                setError(null);
                if (fatsId) loadFATS();
              }}
            >
              Retry
            </Button>
          </Box>
        )}

        {!loading && !error && (fats || mode === 'create') && (
          <Box sx={{ mt: mode === 'create' ? 0 : 2 }}>
            {/* Top Row: Operator, Date, Section, Section2, Status, IDNo (only in view/edit mode) */}
            <Grid container spacing={2} sx={{ mb: 3 }}>
              <Grid item xs={12} sm={2}>
                <FormControl fullWidth>
                  <InputLabel>Operator</InputLabel>
                  <Select
                    value={formData.operator}
                    label="Operator"
                    onChange={handleChange('operator')}
                    disabled={isViewMode}
                  >
                    {staff.map((name) => (
                      <MenuItem key={name} value={name}>{formatOperatorDisplay(name)}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} sm={2.5}>
                <TextField
                  fullWidth
                  label="Date"
                  value={formData.datein}
                  onChange={handleChange('datein')}
                  disabled={isViewMode || mode === 'create'}
                  type="datetime-local"
                  InputLabelProps={{ shrink: true }}
                />
              </Grid>
              <Grid item xs={12} sm={2}>
                <FormControl fullWidth>
                  <InputLabel>Section</InputLabel>
                  <Select
                    value={formData.section || '.none'}
                    label="Section"
                    onChange={handleChange('section')}
                    disabled={isViewMode}
                  >
                    {sections.map((section) => (
                      <MenuItem key={section} value={section}>{formatSectionDisplay(section)}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} sm={2}>
                <FormControl fullWidth>
                  <InputLabel>Section2</InputLabel>
                  <Select
                    value={formData.section2 || '.none'}
                    label="Section2"
                    onChange={handleChange('section2')}
                    disabled={isViewMode}
                  >
                    {sections.map((section) => (
                      <MenuItem key={section} value={section}>{formatSectionDisplay(section)}</MenuItem>
                    ))}
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12} sm={1.5}>
                <FormControl fullWidth>
                  <InputLabel>Status</InputLabel>
                  <Select
                    value={formData.status}
                    label="Status"
                    onChange={handleChange('status')}
                    disabled={isViewMode}
                  >
                    <MenuItem value="Active">Active</MenuItem>
                    <MenuItem value="Canceled">Canceled</MenuItem>
                  </Select>
                </FormControl>
              </Grid>
              {mode !== 'create' && (
                <Grid item xs={12} sm={2}>
                  <TextField
                    fullWidth
                    label="IDNo"
                    value={formData.idno || ''}
                    disabled={true}
                  />
                </Grid>
              )}
            </Grid>

            {/* SECTION 1: ISSUE INFORMATION */}
            <Paper elevation={2} sx={{ p: 3, mb: 4, bgcolor: '#f8f9fa' }}>
              <Typography variant="h6" sx={{ mb: 3, fontWeight: 'bold', color: 'primary.main', borderBottom: '2px solid', borderColor: 'primary.main', pb: 1 }}>
                Issue Information
              </Typography>
              
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>Issue:</Typography>
              <TextField
                fullWidth
                label="Issue"
                value={formData.issue}
                onChange={handleChange('issue')}
                disabled={isViewMode}
                sx={{ mb: 3 }}
              />
              
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>Sections:</Typography>
              <Grid container spacing={2} sx={{ mb: 3 }}>
                <Grid item xs={12} sm={6}>
                  <FormControl fullWidth>
                    <InputLabel>Section</InputLabel>
                    <Select
                      value={formData.section || '.none'}
                      label="Section"
                      onChange={handleChange('section')}
                      disabled={isViewMode}
                    >
                      {sections.map((section) => (
                        <MenuItem key={section} value={section}>{formatSectionDisplay(section)}</MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                </Grid>
                <Grid item xs={12} sm={6}>
                  <FormControl fullWidth>
                    <InputLabel>Section 2</InputLabel>
                    <Select
                      value={formData.section2 || '.none'}
                      label="Section 2"
                      onChange={handleChange('section2')}
                      disabled={isViewMode}
                    >
                      {sections.map((section) => (
                        <MenuItem key={section} value={section}>{formatSectionDisplay(section)}</MenuItem>
                      ))}
                    </Select>
                  </FormControl>
                </Grid>
              </Grid>
              
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>Issue Description:</Typography>
              {isViewMode ? (
                <Box
                  sx={{
                    border: '1px solid #ccc',
                    borderRadius: 1,
                    p: 2,
                    minHeight: 200,
                    bgcolor: '#f5f5f5',
                    '& a': {
                      color: '#1976d2',
                      textDecoration: 'underline',
                      cursor: 'pointer',
                      '&:hover': { color: '#115293' },
                    },
                    '& a[href^="#fault-"]': {
                      color: '#d32f2f',
                      fontWeight: 600,
                      '&::before': {
                        content: '"🔗 "',
                        fontSize: '0.9em',
                      },
                      '&:hover': {
                        color: '#b71c1c',
                        backgroundColor: 'rgba(211, 47, 47, 0.1)',
                        padding: '2px 4px',
                        borderRadius: '3px',
                      },
                    },
                  }}
                  dangerouslySetInnerHTML={{ __html: formData.idescribe || '' }}
                />
              ) : (
                <Box
                  sx={{
                    border: '1px solid #ccc',
                    borderRadius: 1,
                    '& .tiptap': {
                      minHeight: 200,
                      padding: 2,
                      outline: 'none',
                      '& p.is-editor-empty:first-child::before': {
                        color: '#adb5bd',
                        content: 'attr(data-placeholder)',
                        float: 'left',
                        height: 0,
                        pointerEvents: 'none',
                      },
                      '& h1, & h2, & h3': {
                        fontWeight: 'bold',
                        marginTop: '0.5em',
                        marginBottom: '0.5em',
                      },
                      '& ul, & ol': {
                        paddingLeft: '1.5em',
                      },
                      '& a': {
                        color: '#1976d2',
                        textDecoration: 'underline',
                      },
                    },
                    '& .tiptap-menu': {
                      borderBottom: '1px solid #ccc',
                      padding: '8px',
                      display: 'flex',
                      gap: '4px',
                      flexWrap: 'wrap',
                      backgroundColor: '#f5f5f5',
                    },
                  }}
                >
                  {editorIssue && (
                    <>
                      <MenuBar editor={editorIssue} />
                      <EditorContent editor={editorIssue} />
                    </>
                  )}
                </Box>
              )}
            </Paper>

            {/* SECTION 2: ACTION / RESOLUTION */}
            <Paper elevation={2} sx={{ p: 3, bgcolor: '#f0f7ff' }}>
              <Typography variant="h6" sx={{ mb: 3, fontWeight: 'bold', color: 'success.main', borderBottom: '2px solid', borderColor: 'success.main', pb: 1 }}>
                Action / Resolution
              </Typography>
              
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>Action:</Typography>
              <TextField
                fullWidth
                label="Action"
                value={formData.todo}
                onChange={handleChange('todo')}
                disabled={isViewMode}
                sx={{ mb: 3 }}
              />
              
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>Solution:</Typography>
              <TextField
                fullWidth
                label="Solution"
                value={formData.solution}
                onChange={handleChange('solution')}
                disabled={isViewMode}
                sx={{ mb: 3 }}
              />
              
              <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 'bold' }}>Solution Description:</Typography>
                  {isViewMode ? (
                    <Box
                      sx={{
                        border: '1px solid #ccc',
                        borderRadius: 1,
                        p: 2,
                        minHeight: 200,
                        bgcolor: '#f5f5f5',
                        '& a': {
                          color: '#1976d2',
                          textDecoration: 'underline',
                          cursor: 'pointer',
                          '&:hover': { color: '#115293' },
                        },
                        '& a[href^="#fault-"]': {
                          color: '#d32f2f',
                          fontWeight: 600,
                          '&::before': {
                            content: '"🔗 "',
                            fontSize: '0.9em',
                          },
                          '&:hover': {
                            color: '#b71c1c',
                            backgroundColor: 'rgba(211, 47, 47, 0.1)',
                            padding: '2px 4px',
                            borderRadius: '3px',
                          },
                        },
                      }}
                      dangerouslySetInnerHTML={{ __html: formData.sdescribe || '' }}
                    />
                  ) : (
                    <Box
                      sx={{
                        border: '1px solid #ccc',
                        borderRadius: 1,
                        '& .tiptap': {
                          minHeight: 200,
                          padding: 2,
                          outline: 'none',
                          '& p.is-editor-empty:first-child::before': {
                            color: '#adb5bd',
                            content: 'attr(data-placeholder)',
                            float: 'left',
                            height: 0,
                            pointerEvents: 'none',
                          },
                          '& h1, & h2, & h3': {
                            fontWeight: 'bold',
                            marginTop: '0.5em',
                            marginBottom: '0.5em',
                          },
                          '& ul, & ol': {
                            paddingLeft: '1.5em',
                          },
                          '& a': {
                            color: '#1976d2',
                            textDecoration: 'underline',
                          },
                        },
                        '& .tiptap-menu': {
                          borderBottom: '1px solid #ccc',
                          padding: '8px',
                          display: 'flex',
                          gap: '4px',
                          flexWrap: 'wrap',
                          backgroundColor: '#f5f5f5',
                        },
                      }}
                    >
                      {editorSolution && (
                        <>
                          <MenuBar editor={editorSolution} />
                          <EditorContent editor={editorSolution} />
                        </>
                      )}
                    </Box>
                  )}
                  
                  {/* Image Upload Button for Create/Edit Mode - Below Text Editor */}
                  {!isViewMode && (
                    <Box sx={{ mt: 2, mb: 2 }}>
                      <input
                        ref={createImageInputRef}
                        type="file"
                        accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
                        onChange={handleCreateFormImageSelect}
                        style={{ display: 'none' }}
                        id="create-image-upload-input"
                        multiple={true}
                      />
                      <label htmlFor="create-image-upload-input">
                        <Button
                          variant="outlined"
                          component="span"
                          startIcon={<UploadIcon />}
                          disabled={uploadingImage}
                          size="medium"
                          sx={{ 
                            cursor: uploadingImage ? 'not-allowed' : 'pointer',
                            mt: 1
                          }}
                        >
                          {uploadingImage ? 'Uploading...' : 'Select Images from System'}
                        </Button>
                      </label>
                      {pendingImages.length > 0 && (
                        <Box sx={{ mt: 2 }}>
                          <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mb: 1 }}>
                            {pendingImages.length} image(s) selected. They will be uploaded when you save the FATS entry.
                          </Typography>
                          <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 1 }}>
                            {pendingImages.map((file, index) => (
                              <Chip
                                key={index}
                                label={`${file.name} (${(file.size / 1024).toFixed(1)} KB)`}
                                onDelete={() => {
                                  const newPending = [...pendingImages];
                                  newPending.splice(index, 1);
                                  setPendingImages(newPending);
                                }}
                                size="small"
                                color="primary"
                                variant="outlined"
                              />
                            ))}
                          </Box>
                        </Box>
                      )}
                    </Box>
                  )}
              
              {/* Pictures Section */}
              <Divider sx={{ my: 3 }} />
              <Typography variant="subtitle2" sx={{ mb: 2, fontWeight: 'bold' }}>Pictures:</Typography>
              {fats && (
                <Box sx={{ mb: 3 }}>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                    <Typography variant="body2" color="text.secondary">
                      {images.length} image(s)
                    </Typography>
                  {!isViewMode && (
                    <>
                      <input
                        ref={fileInputRef}
                        type="file"
                        accept="image/jpeg,image/jpg,image/png,image/gif,image/webp"
                        onChange={handleImageUpload}
                        style={{ display: 'none' }}
                        id="image-upload-input"
                        multiple={false}
                      />
                      <label htmlFor="image-upload-input">
                        <Button
                          variant="contained"
                          component="span"
                          startIcon={<UploadIcon />}
                          disabled={uploadingImage || !fatsId}
                          size="small"
                          sx={{ 
                            cursor: uploadingImage || !fatsId ? 'not-allowed' : 'pointer',
                            '&:hover': {
                              backgroundColor: uploadingImage || !fatsId ? undefined : 'primary.dark'
                            }
                          }}
                        >
                          {uploadingImage ? 'Uploading...' : 'Upload Image from System'}
                        </Button>
                      </label>
                      {!fatsId && (
                        <Typography variant="caption" color="text.secondary" sx={{ ml: 1 }}>
                          (Save FATS entry first)
                        </Typography>
                      )}
                    </>
                  )}
                </Box>
                {images.length > 0 ? (
                  <ImageList cols={3} gap={8} sx={{ maxHeight: 400, overflow: 'auto' }}>
                    {images.map((image) => (
                      <ImageListItem 
                        key={image.filename}
                        sx={{ cursor: 'pointer' }}
                        onClick={() => {
                          setSelectedImage(image);
                        }}
                      >
                        <img
                          src={image.url ? (image.url.startsWith('http') ? image.url : `${API_BASE_URL}${image.url}`) : fatsAPI.getImageUrl(image.filename)}
                          alt={image.filename}
                          loading="lazy"
                          style={{ width: '100%', height: '200px', objectFit: 'cover' }}
                        />
                        <ImageListItemBar
                          title={image.filename}
                          subtitle={`${new Date(image.uploaded_at).toLocaleDateString()} HST`}
                          actionIcon={
                            !isViewMode && (
                              <IconButton
                                sx={{ color: 'rgba(255, 255, 255, 0.54)' }}
                                onClick={(e) => {
                                  e.stopPropagation(); // Prevent opening image modal when deleting
                                  handleDeleteImage(image.filename);
                                }}
                                size="small"
                              >
                                <DeleteIcon />
                              </IconButton>
                            )
                          }
                        />
                      </ImageListItem>
                    ))}
                  </ImageList>
                ) : (
                  <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'center', py: 2 }}>
                    No pictures yet
                  </Typography>
                )}
                </Box>
              )}
              
              {/* Comments Section */}
              <Divider sx={{ my: 3 }} />
              <Typography variant="subtitle2" sx={{ mb: 2, fontWeight: 'bold' }}>Comments:</Typography>
              {fats && comments.length > 0 ? (
                <Paper variant="outlined" sx={{ p: 2, maxHeight: 300, overflow: 'auto' }}>
                  <List>
                    {comments.map((comment, index) => (
                      <ListItem key={comment.id || index} alignItems="flex-start">
                        <ListItemText
                          primary={
                            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                              <Typography variant="subtitle2">
                                {comment.commenter || 'Anonymous'}
                              </Typography>
                              <Typography variant="caption" color="text.secondary">
                                {formatHSTTimestamp(comment.created_at)}
                              </Typography>
                            </Box>
                          }
                          secondary={
                            <Typography
                              variant="body2"
                              component="div"
                              sx={{ mt: 1, whiteSpace: 'pre-wrap' }}
                            >
                              {cleanDescription(stripHtml(comment.comment_text || ''))}
                            </Typography>
                          }
                        />
                      </ListItem>
                    ))}
                  </List>
                </Paper>
              ) : fats && (
                <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'center', py: 2 }}>
                  No comments yet
                </Typography>
              )}
            </Paper>
          </Box>
        )}
      </DialogContent>
      {mode !== 'create' && (
        <DialogActions>
          <Button onClick={onClose}>{isViewMode ? 'Close' : 'Cancel'}</Button>
          {!isViewMode && (
            <Button
              onClick={handleSaveClick}
              variant="contained"
              disabled={loading || (mode === 'edit' && !formData.idno)}
            >
              {loading ? 'Saving...' : 'Save'}
            </Button>
          )}
        </DialogActions>
      )}

      {/* Image Preview Modal */}
      <Dialog
        open={selectedImage !== null}
        onClose={() => setSelectedImage(null)}
        maxWidth="lg"
        fullWidth
        PaperProps={{
          sx: {
            backgroundColor: 'rgba(0, 0, 0, 0.9)',
            color: 'white',
          }
        }}
                onKeyDown={(e) => {
                  // Keyboard navigation: Arrow keys to navigate between images
                  if (selectedImage && images.length > 1) {
                    const currentIndex = images.findIndex(img => img.filename === selectedImage.filename);
                    if (e.key === 'ArrowLeft' && currentIndex > 0) {
                      setSelectedImage(images[currentIndex - 1]);
                    } else if (e.key === 'ArrowRight' && currentIndex < images.length - 1) {
                      setSelectedImage(images[currentIndex + 1]);
                    } else if (e.key === 'Escape') {
                      setSelectedImage(null);
                    }
                  }
                }}
        tabIndex={0}
      >
        {selectedImage && (
          <>
            <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="h6" component="div" sx={{ flex: 1, textAlign: 'center' }}>
                  {selectedImage.filename}
                  {images.length > 1 && (
                    <Typography variant="caption" component="div" sx={{ opacity: 0.7, mt: 0.5 }}>
                      {images.findIndex(img => img.filename === selectedImage.filename) + 1} of {images.length}
                    </Typography>
                  )}
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                <Typography variant="body2" sx={{ color: 'rgba(255, 255, 255, 0.7)', mr: 1 }}>
                  {Math.round(imageZoom * 100)}%
                </Typography>
                <IconButton
                  onClick={(e) => {
                    if (imageContainerRef.current) {
                      const rect = imageContainerRef.current.getBoundingClientRect();
                      const x = ((e.clientX - rect.left) / rect.width - 0.5) * 100;
                      const y = ((e.clientY - rect.top) / rect.height - 0.5) * 100;
                      setImagePosition({ x, y });
                      setImageZoom(prev => Math.min(prev + 0.25, 3));
                    }
                  }}
                  sx={{ 
                    color: 'white',
                    '&:hover': { backgroundColor: 'rgba(255, 255, 255, 0.1)' }
                  }}
                  aria-label="Zoom in"
                  title="Zoom in"
                >
                  <ZoomIn />
                </IconButton>
                <IconButton
                  onClick={() => {
                    setImageZoom(prev => {
                      const newZoom = Math.max(prev - 0.25, 0.5);
                      if (newZoom <= 1) {
                        setImagePosition({ x: 0, y: 0 }); // Reset position when zoomed out
                      }
                      return newZoom;
                    });
                  }}
                  disabled={imageZoom <= 0.5}
                  sx={{ 
                    color: 'white',
                    '&:hover': { backgroundColor: 'rgba(255, 255, 255, 0.1)' },
                    '&.Mui-disabled': { color: 'rgba(255, 255, 255, 0.3)' }
                  }}
                  aria-label="Zoom out"
                  title="Zoom out"
                >
                  <ZoomOut />
                </IconButton>
                <Button
                  onClick={() => {
                    setSelectedImage(null);
                    setImageZoom(1); // Reset zoom when closing
                    setImagePosition({ x: 0, y: 0 }); // Reset position
                  }}
                  sx={{ color: 'white', minWidth: 'auto', ml: 1 }}
                  aria-label="Close"
                >
                  ✕
                </Button>
              </Box>
            </DialogTitle>
            <DialogContent 
              sx={{ 
                textAlign: 'center', 
                p: 2, 
                position: 'relative', 
                overflow: 'hidden',
                height: '70vh',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                cursor: imageZoom > 1 ? (isDragging ? 'grabbing' : 'grab') : 'default',
              }}
              onWheel={(e) => {
                if (e.ctrlKey || e.metaKey) {
                  e.preventDefault();
                  const delta = e.deltaY > 0 ? -0.1 : 0.1;
                  const newZoom = Math.max(0.5, Math.min(3, imageZoom + delta));
                  
                  if (imageContainerRef.current) {
                    const rect = imageContainerRef.current.getBoundingClientRect();
                    const x = ((e.clientX - rect.left) / rect.width - 0.5) * 100;
                    const y = ((e.clientY - rect.top) / rect.height - 0.5) * 100;
                    setImagePosition({ x, y });
                  }
                  
                  setImageZoom(newZoom);
                }
              }}
            >
              {/* Previous button on left side */}
                {images.length > 1 && (
                  <IconButton
                    onClick={() => {
                      const currentIndex = images.findIndex(img => img.filename === selectedImage.filename);
                      if (currentIndex > 0) {
                        setSelectedImage(images[currentIndex - 1]);
                        setImageZoom(1); // Reset zoom when switching images
                        setImagePosition({ x: 0, y: 0 }); // Reset position
                      }
                    }}
                    disabled={images.findIndex(img => img.filename === selectedImage.filename) === 0}
                  sx={{
                    position: 'absolute',
                    left: 16,
                    top: '50%',
                    transform: 'translateY(-50%)',
                    color: 'white',
                    backgroundColor: 'rgba(0, 0, 0, 0.5)',
                    '&:hover': { 
                      backgroundColor: 'rgba(0, 0, 0, 0.7)',
                    },
                    '&.Mui-disabled': { 
                      color: 'rgba(255, 255, 255, 0.3)',
                      backgroundColor: 'rgba(0, 0, 0, 0.2)'
                    },
                    zIndex: 1,
                  }}
                  aria-label="Previous image"
                >
                  <ChevronLeft fontSize="large" />
                </IconButton>
              )}
              
              <Box
                ref={imageContainerRef}
                sx={{
                  position: 'relative',
                  width: '100%',
                  height: '100%',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  overflow: 'auto',
                }}
                onMouseDown={(e) => {
                  if (imageZoom > 1 && e.button === 0) {
                    setIsDragging(true);
                    setDragStart({
                      x: e.clientX - imagePosition.x,
                      y: e.clientY - imagePosition.y,
                    });
                  }
                }}
                onMouseMove={(e) => {
                  if (isDragging && imageZoom > 1) {
                    const newX = e.clientX - dragStart.x;
                    const newY = e.clientY - dragStart.y;
                    setImagePosition({ x: newX, y: newY });
                  }
                }}
                onMouseUp={() => {
                  setIsDragging(false);
                }}
                onMouseLeave={() => {
                  setIsDragging(false);
                }}
                onClick={(e) => {
                  // Double-click to zoom in at click position
                  if (e.detail === 2) {
                    const rect = imageContainerRef.current.getBoundingClientRect();
                    const x = ((e.clientX - rect.left) / rect.width - 0.5) * 100;
                    const y = ((e.clientY - rect.top) / rect.height - 0.5) * 100;
                    setImagePosition({ x, y });
                    setImageZoom(prev => Math.min(prev + 0.5, 3));
                  }
                }}
              >
                <Box
                  sx={{
                    display: 'inline-block',
                    transform: `scale(${imageZoom}) translate(${imagePosition.x}px, ${imagePosition.y}px)`,
                    transformOrigin: 'center center',
                    transition: isDragging ? 'none' : 'transform 0.2s ease-in-out',
                    maxWidth: '100%',
                    maxHeight: '100%',
                  }}
                >
              <img
                src={selectedImage.url ? (selectedImage.url.startsWith('http') ? selectedImage.url : `${API_BASE_URL}${selectedImage.url}`) : fatsAPI.getImageUrl(selectedImage.filename)}
                alt={selectedImage.filename}
                    style={{
                      maxWidth: '100%',
                      maxHeight: '70vh',
                      objectFit: 'contain',
                      borderRadius: '4px',
                      display: 'block',
                      userSelect: 'none',
                      pointerEvents: 'none',
                    }}
                    draggable={false}
                  />
                </Box>
              </Box>
              
              {/* Next button on right side */}
              {images.length > 1 && (
                <IconButton
                  onClick={() => {
                    const currentIndex = images.findIndex(img => img.filename === selectedImage.filename);
                    if (currentIndex < images.length - 1) {
                      setSelectedImage(images[currentIndex + 1]);
                      setImageZoom(1); // Reset zoom when switching images
                      setImagePosition({ x: 0, y: 0 }); // Reset position
                    }
                  }}
                  disabled={images.findIndex(img => img.filename === selectedImage.filename) === images.length - 1}
                  sx={{
                    position: 'absolute',
                    right: 16,
                    top: '50%',
                    transform: 'translateY(-50%)',
                    color: 'white',
                    backgroundColor: 'rgba(0, 0, 0, 0.5)',
                    '&:hover': { 
                      backgroundColor: 'rgba(0, 0, 0, 0.7)',
                    },
                    '&.Mui-disabled': { 
                      color: 'rgba(255, 255, 255, 0.3)',
                      backgroundColor: 'rgba(0, 0, 0, 0.2)'
                    },
                    zIndex: 1,
                  }}
                  aria-label="Next image"
                >
                  <ChevronRight fontSize="large" />
                </IconButton>
              )}
              
              <Box sx={{ mt: 2, color: 'rgba(255, 255, 255, 0.7)' }}>
                <Typography variant="body2">
                  Uploaded: {formatHSTTimestamp(selectedImage.uploaded_at)}
                </Typography>
                {selectedImage.uploaded_by && (
                  <Typography variant="body2">
                    By: {selectedImage.uploaded_by}
                  </Typography>
                )}
                {selectedImage.file_size && (
                  <Typography variant="body2">
                    Size: {(selectedImage.file_size / 1024).toFixed(2)} KB
                  </Typography>
                )}
              </Box>
            </DialogContent>
          </>
        )}
      </Dialog>
    </Dialog>
    </>
  );
};

export default FATSDetail;



