"""
Pydantic schemas for FATS entries
"""
from pydantic import BaseModel, Field, field_validator
from typing import Optional, List
from datetime import datetime
# from app.models.fats_entry import FATSStatus, FATSPriority

class FATSEntryBase(BaseModel):
    """Base FATS entry schema"""
    idno: int = Field(..., description="FATS ID number (legacy: int)")
    issue: Optional[str] = Field(None, max_length=500)
    idescribe: Optional[str] = None
    solution: Optional[str] = Field(None, max_length=500)
    sdescribe: Optional[str] = None
    todo: Optional[str] = Field(None, max_length=80)  # Added to match legacy
    section: Optional[str] = Field(None, max_length=100)
    operator: Optional[str] = Field(None, max_length=20)  # Added to match legacy
    status: str = "Active"
    section2: Optional[str] = Field(None, max_length=30)  # Added to match legacy
    assigned_to: Optional[str] = Field(None, max_length=100)
    created_by: Optional[str] = Field(None, max_length=100)

class FATSEntryCreate(BaseModel):
    """Schema for creating FATS entries - idno is optional (auto-generated by database)"""
    idno: Optional[int] = Field(None, description="FATS ID number (optional, auto-generated if not provided)")
    issue: Optional[str] = Field(None, max_length=500)
    idescribe: Optional[str] = None
    solution: Optional[str] = Field(None, max_length=500)
    sdescribe: Optional[str] = None
    todo: Optional[str] = Field(None, max_length=80)  # Added to match legacy
    section: Optional[str] = Field(None, max_length=100)
    operator: Optional[str] = Field(None, max_length=20)  # Added to match legacy
    status: str = "Active"
    section2: Optional[str] = Field(None, max_length=30)  # Added to match legacy
    assigned_to: Optional[str] = Field(None, max_length=100)
    created_by: Optional[str] = Field(None, max_length=100)

class FATSEntryUpdate(BaseModel):
    """Schema for updating FATS entries"""
    issue: Optional[str] = Field(None, max_length=500)
    idescribe: Optional[str] = None
    solution: Optional[str] = Field(None, max_length=500)
    sdescribe: Optional[str] = None
    section: Optional[str] = Field(None, max_length=100)
    status: Optional[str] = None
    assigned_to: Optional[str] = Field(None, max_length=100)
    resolved_at: Optional[datetime] = None

class FATSEntryResponse(FATSEntryBase):
    """Schema for FATS entry responses - maps legacy field names"""
    datein: Optional[datetime] = None  # Handle invalid dates like 0000-00-00
    likes: int = 0
    dislikes: int = 0
    views: int = 0  # Added to match legacy
    is_blank: bool = False
    created_at: Optional[datetime] = None  # Maps to datein
    updated_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    
    @field_validator('datein', 'created_at', 'updated_at', 'resolved_at', mode='before')
    @classmethod
    def handle_invalid_dates(cls, v):
        """Handle invalid dates like 0000-00-00 00:00:00 from legacy database"""
        if v is None:
            return None
        if isinstance(v, str) and v.startswith('0000-00-00'):
            return None
        return v
    
    class Config:
        from_attributes = True
        # Allow conversion from int idno to string for API compatibility
        populate_by_name = True

class FATSEntryWithComments(FATSEntryResponse):
    """FATS entry with comments"""
    comments: List["FATSCommentResponse"] = []

class FATSCommentBase(BaseModel):
    """Base FATS comment schema"""
    todo: Optional[str] = Field(None, max_length=80)  # Added to match legacy
    solution: Optional[str] = Field(None, max_length=80)  # Added to match legacy
    comment_text: str = Field(..., description="Comment text", min_length=1)
    commenter: Optional[str] = Field(None, max_length=100)

class FATSCommentCreate(FATSCommentBase):
    """Schema for creating FATS comments"""
    # Note: fats_id is NOT included here - it comes from the URL path parameter
    # This prevents validation conflicts when fats_id is sent in both URL and body

class FATSCommentUpdate(BaseModel):
    """Schema for updating FATS comments - all fields optional"""
    todo: Optional[str] = Field(None, max_length=80)
    solution: Optional[str] = Field(None, max_length=80)
    comment_text: Optional[str] = Field(None, description="Comment text", min_length=1)
    commenter: Optional[str] = Field(None, max_length=100)

class FATSCommentResponse(BaseModel):
    """Schema for FATS comment responses - maps legacy field names to API-friendly names"""
    id: int  # Maps from legacy idno
    fats_id: int  # Maps from legacy faultidno
    todo: Optional[str] = None
    solution: Optional[str] = None
    comment_text: str  # Maps from legacy sdescribe
    commenter: Optional[str] = None  # Maps from legacy operator
    created_at: datetime  # Maps from legacy datein
    
    @classmethod
    def from_legacy_model(cls, comment: "FATSComment"):
        """Create response from legacy model"""
        # Ensure fats_id is int (faultidno should be int in legacy)
        fats_id = int(comment.faultidno) if comment.faultidno is not None else None
        
        return cls(
            id=comment.idno,
            fats_id=fats_id,
            todo=comment.todo,
            solution=comment.solution,
            comment_text=comment.sdescribe or "",
            commenter=comment.operator,
            created_at=comment.datein
        )
    
    class Config:
        from_attributes = True

# Update forward references
FATSEntryWithComments.model_rebuild()
